version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/atphotobackend
  
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop-application.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start-application.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate-service.sh
      timeout: 300
      runas: root
